version: '2'

networks:
  proxy:
    external: true
  internal:
    external: false

services:
  data:
    build: data
    hostname: ckan-data
    container_name: ckan-data
    networks:
      - internal
    labels:
      - traefik.enable=false

  postgres:
    image: postgres:latest
    container_name: ckan-postgres
    hostname: ckan-postgres
    env_file: .env
    volumes:
      - ./postgres/create_ckan_database_objects.sh:/docker-entrypoint-initdb.d/create_ckan_database_objects.sh
      - ./postgres/setup_remote_connections.sh:/docker-entrypoint-initdb.d/setup_remote_connections.sh
    networks:
      - internal
    labels:
      - traefik.enable=false

  solr:
    image: solr:5.5
    container_name: ckan-solr
    hostname: ckan-solr
    volumes:
      - ./solr/ckan:/opt/solr/server/solr/ckan
    networks:
      - internal
    labels:
      - traefik.enable=false

  datapusher:
    build: datapusher
    hostname: ckan-datapusher
    container_name: ckan-datapusher
    networks:
      - internal
    labels:
      - traefik.enable=false

  ckan:
    build: .
    container_name: ckan-app
    hostname: ckan-app
    expose:
      - "8000"
    depends_on:
      - postgres
      - solr
    links:
      - postgres:ckan-postgres
      - solr:ckan-solr
      - datapusher:ckan-datapusher
    volumes_from:
      - data
    volumes:
      - ./setup/production.ini:/srv/app/production.ini
    env_file: .env
    networks:
      - internal
      - proxy
    labels:
      - traefik.backend=ckan
      - traefik.frontend.rule=Host:ckan.opendataprocessor.com
      - traefik.docker.network=proxy
      - traefik.port=8000

networks:
  ckan_network:
    external: true