version: '2'

services:
  data:
    build: data
    hostname: ckan-data
    networks: 
      - ckan
    container_name: ckan-data

  postgres:
    image: postgres:latest
    container_name: ckan-postgres
    hostname: ckan-postgres
    env_file: .env
    networks: 
      - ckan
    volumes:
      - ./postgres/create_ckan_database_objects.sh:/docker-entrypoint-initdb.d/create_ckan_database_objects.sh
      - ./postgres/setup_remote_connections.sh:/docker-entrypoint-initdb.d/setup_remote_connections.sh

  solr:
    image: solr:5.5
    container_name: ckan-solr
    hostname: ckan-solr
    networks: 
      - ckan
    volumes:
      - ./solr/ckan:/opt/solr/server/solr/ckan

  datapusher:
    build: datapusher
    hostname: ckan-datapusher
    networks: 
      - ckan
    container_name: ckan-datapusher

  ckan:
    build: .
    container_name: ckan-app
    hostname: ckan-app
    networks: 
      - ckan
    ports:
      - "8000"
    depends_on:
      - postgres
      - solr
    links:
      - postgres:ckan-postgres
      - solr:ckan-solr
      - datapusher:ckan-datapusher
    volumes_from:
      - data
    volumes:
      - ./setup/production.ini:/srv/app/production.ini
    env_file: .env
